import requests
import json
import time
import urllib3

urllib3.disable_warnings()

# =====================================
# CONFIG
# =====================================

TOKEN_URL = "YOUR_TOKEN_URL"
CLIENT_ID = "YOUR_CLIENT_ID"
CLIENT_SECRET = "YOUR_CLIENT_SECRET"
SCOPE = "YOUR_SCOPE"

FHIR_BASE = "https://fhir-ehr-code.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d"

TOKEN_REFRESH_SECONDS = 480

# =====================================
# TOKEN MANAGEMENT
# =====================================

access_token = None
token_created = 0


def get_access_token():

    response = requests.post(
            TOKEN_URL,
                    auth=(CLIENT_ID, CLIENT_SECRET),
                            data={
                                        "grant_type": "client_credentials",
                                                    "scope": SCOPE
                                                            },
                                                                    verify=False,
                                                                            timeout=60
                                                                                )

                                                                                    response.raise_for_status()

                                                                                        token = response.json()["access_token"]

                                                                                            print("New token generated")

                                                                                                return token


                                                                                                def ensure_token():

                                                                                                    global access_token
                                                                                                        global token_created

                                                                                                            if (
                                                                                                                    access_token is None
                                                                                                                            or time.time() - token_created > TOKEN_REFRESH_SECONDS
                                                                                                                                ):
                                                                                                                                        access_token = get_access_token()
                                                                                                                                                token_created = time.time()

                                                                                                                                                    return access_token


                                                                                                                                                    def call_api(url):

                                                                                                                                                        global access_token
                                                                                                                                                            global token_created

                                                                                                                                                                ensure_token()

                                                                                                                                                                    headers = {
                                                                                                                                                                            "Authorization": f"Bearer {access_token}",
                                                                                                                                                                                    "Accept": "application/json"
                                                                                                                                                                                        }

                                                                                                                                                                                            response = requests.get(
                                                                                                                                                                                                    url,
                                                                                                                                                                                                            headers=headers,
                                                                                                                                                                                                                    verify=False,
                                                                                                                                                                                                                            timeout=120
                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                    if response.status_code == 401:

                                                                                                                                                                                                                                            print("401 detected. Refreshing token...")

                                                                                                                                                                                                                                                    access_token = get_access_token()
                                                                                                                                                                                                                                                            token_created = time.time()

                                                                                                                                                                                                                                                                    headers["Authorization"] = f"Bearer {access_token}"

                                                                                                                                                                                                                                                                            response = requests.get(
                                                                                                                                                                                                                                                                                        url,
                                                                                                                                                                                                                                                                                                    headers=headers,
                                                                                                                                                                                                                                                                                                                verify=False,
                                                                                                                                                                                                                                                                                                                            timeout=120
                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                        return response


                                                                                                                                                                                                                                                                                                                                        # =====================================
                                                                                                                                                                                                                                                                                                                                        # RESUME SUPPORT
                                                                                                                                                                                                                                                                                                                                        # =====================================

                                                                                                                                                                                                                                                                                                                                        all_practitioners = []
                                                                                                                                                                                                                                                                                                                                        start_url = f"{FHIR_BASE}/Practitioner?active=true"

                                                                                                                                                                                                                                                                                                                                        try:

                                                                                                                                                                                                                                                                                                                                            with open("practitioner_checkpoint.json", "r", encoding="utf-8") as f:

                                                                                                                                                                                                                                                                                                                                                    checkpoint = json.load(f)

                                                                                                                                                                                                                                                                                                                                                            all_practitioners = checkpoint["data"]
                                                                                                                                                                                                                                                                                                                                                                    start_url = checkpoint["next_url"]

                                                                                                                                                                                                                                                                                                                                                                            print(
                                                                                                                                                                                                                                                                                                                                                                                        f"Checkpoint loaded. "
                                                                                                                                                                                                                                                                                                                                                                                                    f"{len(all_practitioners)} practitioners already saved."
                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                            except:

                                                                                                                                                                                                                                                                                                                                                                                                                print("No checkpoint found. Starting fresh.")

                                                                                                                                                                                                                                                                                                                                                                                                                # =====================================
                                                                                                                                                                                                                                                                                                                                                                                                                # EXTRACTION
                                                                                                                                                                                                                                                                                                                                                                                                                # =====================================

                                                                                                                                                                                                                                                                                                                                                                                                                url = start_url
                                                                                                                                                                                                                                                                                                                                                                                                                page = 0

                                                                                                                                                                                                                                                                                                                                                                                                                while url:

                                                                                                                                                                                                                                                                                                                                                                                                                    page += 1

                                                                                                                                                                                                                                                                                                                                                                                                                        print("\n" + "=" * 50)
                                                                                                                                                                                                                                                                                                                                                                                                                            print("PAGE:", page)
                                                                                                                                                                                                                                                                                                                                                                                                                                print("=" * 50)

                                                                                                                                                                                                                                                                                                                                                                                                                                    response = call_api(url)

                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Status:", response.status_code)

                                                                                                                                                                                                                                                                                                                                                                                                                                            if response.status_code != 200:

                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("ERROR")
                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(response.text[:1000])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bundle = response.json()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            entries = bundle.get("entry", [])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Records on page:", len(entries))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    all_practitioners.extend(entries)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        next_url = None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for link in bundle.get("link", []):

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if link.get("relation") == "next":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                next_url = link.get("url")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Save checkpoint after every page

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with open(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "practitioner_checkpoint.json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "w",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            encoding="utf-8"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) as f:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        json.dump(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "next_url": next_url,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "data": all_practitioners
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f"Total practitioners collected: "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"{len(all_practitioners)}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                url = next_url

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # =====================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # FINAL SAVE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # =====================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "all_practitioners.json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "w",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            encoding="utf-8"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) as f:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                json.dump(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        all_practitioners,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        indent=2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("\nDONE")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f"TOTAL PRACTITIONERS = {len(all_practitioners)}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )